enum ActivityCommentEnum{
  LOADING,INITIAL,ERROR,
  ADD_COMMENT,
  DELETE_COMMENT,
  UPDATE_COMMENT
  ,GET_COMMENTS,
  GET_COMMENT_BY_ID,ADD_REPLY,DELETE_REPLY,UPDATE_REPLY,GET_REPLIES,GET_REPLY_BY_ID, ADD_EMOJI, UpdateEmoji, SEND_NOTIFICATION
}