name: jci_app
description: JCi app is ann app for JCI members to connect and share ideas
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  flutter_localization:
  path_to_regexp:
  freezed:
  image_picker: ^1.0.7
  jwt_decoder:
  url_launcher:
  flutter_countdown_timer:
  dotted_border:
  bloc_concurrency: ^0.2.0
  stream_transform: ^2.0.0
    # Bloc for state management
  flutter_bloc: ^8.1.2
  connectivity_plus:
  # Functional programming things
  dartz: ^0.10.1
  # Value equality
  equatable: ^2.0.5
  json_serializable:
  image:
  flutter_web_browser: ^0.16.0
  # Service locator
  get_it: ^7.6.0
  firebase_core:
  firebase_auth:
  google_sign_in:

  # Remote API
  internet_connection_checker: ^1.0.0+1
  http:
  flutter_svg:
  dropdown_button2: ^2.3.8
  circle_progress_bar: ^0.1.1
  formz:
  intl:
  file_picker:
  open_file:
  # Local cache
  shared_preferences: ^2.1.1
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  mockito:
  secure_shared_preferences: ^0.0.4
  google_fonts: ^4.0.4
  go_router: ^13.1.0
  carousel_slider: ^4.2.1
  smooth_page_indicator: ^1.1.0
  flutter_secure_storage: ^5.1.2

  json_annotation: ^4.8.1
  jwt_decode:
  google_nav_bar: ^5.0.6
  shimmer: ^3.0.0
  permission_handler:


  flutter_time_picker_spinner: ^2.0.0
  table_calendar: ^3.0.9
  flutter_animate: ^4.5.0
dev_dependencies:
  flutter_test:


    sdk: flutter

  build_runner:
  flutter_lints: ^2.0.0
  flutter_launcher_icons: "^0.13.1"
flutter_launcher_icons:
    android: "launcher_icon"
    ios: true
    image_path: "assets/images/icon_p.png"
    min_sdk_android: 21 # android min sdk min:16, default 21

    macos:
      generate: true
      image_path: "assets/images/icon_p.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/jci.png
    - assets/images/icon_p.png
    - assets/images/us.png
    - assets/images/goal.png
    - assets/images/vision.png
    - assets/images/HENRY.jpg
    - assets/images/jciHammem.webp
    - assets/images/jciTunisie.jpg
    - assets/images/Person_Vip.png
    - assets/images/task.jpg

    - assets/images/blankjci.jpeg
    - assets/images/classement.jpg
    - assets/images/cap.png
    - assets/json/
    - assets/lang/en.json
    - assets/lang/fr.json


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
