name: jci_app
description: JCi app is ann app for JCI members to connect and share ideas
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  flutter_localization:

  faker:
  path_to_regexp:
  freezed:
  timeago:
  pinput:
  simple_animation_progress_bar: "^1.8.2"
  flutter_dotenv:
  googleapis:
  auto_route:
  webview_flutter:
  googleapis_auth:
  flutter_screenutil:
  image_picker: ^1.0.7
  collection:
  url_launcher:
  flutter_countdown_timer:
  dotted_border:
  hive:
  hive_flutter:
  bloc_concurrency: ^0.3.0
  stream_transform: ^2.0.0
  font_awesome_flutter:
  firebase_data_connect:
  firebase_messaging:
  google_mlkit_translation:
  firebase_storage:
  firebase_database:
  google_maps_flutter:
  google_places_flutter:
  cloud_functions:
  firebase_performance: ^0.10.1+6
  firebase_remote_config:
  firebase_in_app_messaging:

  firebase_dynamic_links:


  google_api_headers:
    # Bloc for state management
  flutter_bloc: ^9.1.0
  connectivity_plus:
  logger: ^2.5.0
  cloud_firestore:
  # Functional programming things
  dartz: ^0.10.1
  # Value equality
  equatable: ^2.0.5
  json_serializable:
  image:

  # Service locator
  get_it: ^8.0.3
  firebase_core:
  firebase_auth:
  google_sign_in:

  # Remote API
  internet_connection_checker: ^3.0.1
  http:
  flutter_svg:
  dropdown_button2: ^2.3.8
  circle_progress_bar: ^0.1.1
  formz:
  intl:
  file_picker:
  open_file:
  # Local cache
  shared_preferences: ^2.1.1
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  mockito:
  comment_tree:
  encrypt_shared_preferences: ^0.9.9
  google_fonts: ^6.2.1

  carousel_slider:
  smooth_page_indicator: ^1.1.0
  flutter_local_notifications:

  json_annotation: ^4.8.1
  jwt_decode:
  google_nav_bar: ^5.0.6
  shimmer: ^3.0.0

  cached_network_image:

  flutter_time_picker_spinner: ^2.0.0
  table_calendar: ^3.0.9
  flutter_animate: ^4.5.0
  firebase_app_check: ^0.3.1+4
  flutter_chat_reactions: ^0.1.0
  flutter_slidable: ^3.1.1
  emoji_picker_flutter: ^4.3.0
  auto_size_text: ^3.0.0
  flutter_typeahead: ^5.2.0
  syncfusion_flutter_calendar: ^30.2.5
  showcaseview: ^4.0.1

dev_dependencies:
  bloc_test:
  flutter_test:


    sdk: flutter
  analyzer: ^6.7.0
  auto_route_generator:
  build_runner:
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3
flutter_launcher_icons:
    android: "launcher_icon"
    ios: true
    image_path: "assets/images/icon_p.png"
    min_sdk_android: 21 # android min sdk min:16, default 21

    macos:
      generate: true
      image_path: "assets/images/icon_p.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/jci.png
    - assets/images/icon_p.png
    - assets/images/us.png
    - assets/images/goal.png
    - assets/images/vision.png
    - assets/images/HENRY.jpg
    - assets/images/jciHammem.webp
    - assets/images/jciTunisie.jpg
    - assets/images/Person_Vip.png
    - assets/images/task.jpg
    - assets/images/team.png
    - assets/images/Mail.png
    - assets/images/MailSenti.png
    - .env
    - assets/images/blankjci.jpeg
    - assets/images/classement.jpg
    - assets/images/cap.png
    - assets/images/Hello.png
    - assets/imagesf/no_notification.png
    - assets/json/
    - assets/lang/en.json
    - assets/lang/fr.json


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
